acs_store/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'acs_store'
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls", namespace="products")),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts'), namespace="accounts")),
    path('auth/', include('authentication.urls', namespace="auth")),
]

products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import IndexView, ProductsListView, SalesListView, SaleCreateView

app_name = 'products'
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('products-list/', ProductsListView.as_view(), name="products-list"),
    path('sales-list/', SalesListView.as_view(), name='sales-list'),
    path('sale-create/', SaleCreateView.as_view(), name='sale-create'),
]

products/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class Product(models.Model):
    title = models.CharField(verbose_name=_("Product title"), max_length=255, blank=False, null=False)
    category = models.ForeignKey("Category", verbose_name=_("Product category"), blank=False, null=False, related_name="product_category", on_delete=models.PROTECT)
    amount = models.PositiveIntegerField(verbose_name=_("Product amount"), blank=False, null=False)
    price = models.FloatField(verbose_name=_("Product price"), blank=False, null=False)
    shop = models.ForeignKey("Shop", verbose_name=_("Product shop"), blank=False, null=False, related_name="product_shop", on_delete=models.PROTECT)

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return f"{self.title}"


class Category(models.Model):
    title = models.CharField(verbose_name=_("Category title"), max_length=255, blank=False, null=False)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return f"{self.title}"


class Shop(models.Model):
    address = models.CharField(verbose_name=_("Shop address"), max_length=255, blank=False, null=False)

    class Meta:
        verbose_name = _("Shop")
        verbose_name_plural = _("Shops")

    def __str__(self):
        return f"{self.address}"


class Sale(models.Model):
    date_time = models.DateTimeField(verbose_name=_("Sale date and time"), auto_now_add=True)
    product = models.ForeignKey("Product", verbose_name=_("Sale product"), blank=False, null=False, related_name="sale_product", on_delete=models.PROTECT)
    amount = models.PositiveIntegerField(verbose_name=_("Sale amount"), blank=False, null=False)
    price = models.FloatField(verbose_name=_("Sale price"), blank=False, null=False)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = _("Sale")
        verbose_name_plural = _("Sales")

    def __str__(self):
        return f"{self.product}"

products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, TemplateView

from .models import Product, Sale, Category, Shop, User


class IndexView(TemplateView):
    template_name = 'products/index.html'


class ProductsListView(LoginRequiredMixin, TemplateView):
    template_name = "products/product_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        context['categories'] = Category.objects.all()
        context['shops'] = Shop.objects.all()
        prod_title = self.request.GET.get('title', '')

        category = self.request.GET.get('category', '')
        shop = self.request.GET.get('shop', '')

        context['category_pk'] = -1
        context['shop_pk'] = -1
        price1 = self.request.GET.get('min_price', 0.0)
        price2 = self.request.GET.get('max_price', 0.0)

        if prod_title or category or shop or price1 or price2:
            if prod_title != '':
                products = products.filter(title__icontains=prod_title)
            if category != '-1':
                products = products.filter(category_id=category)
                context['category_pk'] = int(category)
            if shop != '-1':
                products = products.filter(shop_id=shop)
                context['shop_pk'] = int(shop)
            if price2 != '' and price1 != '':
                products = products.filter(price__range=(price1, price2))
            context['products'] = products
        else:
            context['products'] = products
        return context


class SalesListView(LoginRequiredMixin, TemplateView):
    template_name = "products/sales_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['categories'] = Category.objects.all()
        context['shops'] = Shop.objects.all()
        context['users'] = User.objects.all()
        sales = Sale.objects.all()

        sale_cat_form_select = self.request.GET.get('sale_cat', '')
        sale_shop_form_select = self.request.GET.get('sale_shop', '')
        sale_user_form_select = self.request.GET.get('sale_user', '')

        context['cat_pk'] = -1
        context['shop_pk'] = -1
        context['user_pk'] = -1

        if sale_cat_form_select.isdigit() and sale_cat_form_select != '-1':
            sales = sales.filter(product__category_id=sale_cat_form_select)
            context['cat_pk'] = int(sale_cat_form_select)

        if sale_shop_form_select.isdigit() and sale_shop_form_select != '-1':
            sales = sales.filter(product__shop_id=sale_shop_form_select)
            context['shop_pk'] = int(sale_shop_form_select)

        if sale_user_form_select.isdigit() and sale_user_form_select != '-1':
            sales = sales.filter(seller_id=sale_user_form_select)
            context['user_pk'] = int(sale_user_form_select)

        context['sales'] = sales
        return context


class SaleCreateView(LoginRequiredMixin, CreateView):
    model = Sale
    fields = ['product', 'amount', 'price']
    template_name = 'products/sale_create.html'

    def form_valid(self, form):
        product = form.cleaned_data['product']
        amount = form.cleaned_data['amount']
        form.instance.seller = self.request.user
        if product.amount >= amount:
            obj = form.save()
            product.amount -= amount
            obj.save()
            product.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)

    def get_success_url(self):
        return reverse('products:sales-list')

products/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{%  static '/img/favicon.ico' %}">


    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block header %}
    {% include "base/header.html" %}
    {% endblock %}
    <div class="container container-margin-top-header">
        {% block content %}
        Here goes content
        {% endblock %}
    </div>
</body>
</html>

products/templates/base/header.html
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">ACS STORE</a>

    <div class="collapse navbar-collapse" id="navbarsExample07">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:products-list' %}">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:sales-list' %}">Sales</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products:sale-create' %}">Create Sale</a>
        </li>
          <li>
              {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.get_username }} <i class="fa fa-sign-out" style="font-size:18px"></i> </a>
                  {% else %}
                  <a class="nav-link" href="{% url 'accounts:login' %}"> log in <i class="fa fa-sign-in" style="font-size:18px"></i> </a>
              {% endif %}
          </li>
      </ul>
    </div>
  </div>
</nav>